#ACUMOS
#================================================================================
#Copyright Â© 2018 AT&T Intellectual Property. All rights reserved.
#================================================================================
#This Acumos software file is distributed by AT&Tunder the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#This file is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and 
#limitations under the License.


# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataPipelineServiceProcessorType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PUBLISH_PROCESSOR = "PUBLISH_PROCESSOR"
    SUBSCRIBE_PROCESSOR = "SUBSCRIBE_PROCESSOR"
    TRANSFORM_PROCESSOR = "TRANSFORM_PROCESSOR"
    SINKER_PROCESSOR = "SINKER_PROCESSOR"

    def __init__(self):  # noqa: E501
        """DataPipelineServiceProcessorType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceProcessorType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceProcessorType of this DataPipelineServiceProcessorType.  # noqa: E501
        :rtype: DataPipelineServiceProcessorType
        """
        return util.deserialize_model(dikt, cls)
