# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.byte_array import ByteArray  # noqa: F401,E501
from swagger_server.models.data_pipeline_service_processor_type import DataPipelineServiceProcessorType  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class DataPipelineServiceProcessorPayload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: DataPipelineServiceProcessorType=None, filename: str=None, string_encoded_payload: ByteArray=None):  # noqa: E501
        """DataPipelineServiceProcessorPayload - a model defined in Swagger

        :param type: The type of this DataPipelineServiceProcessorPayload.  # noqa: E501
        :type type: DataPipelineServiceProcessorType
        :param filename: The filename of this DataPipelineServiceProcessorPayload.  # noqa: E501
        :type filename: str
        :param string_encoded_payload: The string_encoded_payload of this DataPipelineServiceProcessorPayload.  # noqa: E501
        :type string_encoded_payload: ByteArray
        """
        self.swagger_types = {
            'type': DataPipelineServiceProcessorType,
            'filename': str,
            'string_encoded_payload': ByteArray
        }

        self.attribute_map = {
            'type': 'type',
            'filename': 'filename',
            'string_encoded_payload': 'string_encoded_payload'
        }

        self._type = type
        self._filename = filename
        self._string_encoded_payload = string_encoded_payload

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceProcessorPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceProcessorPayload of this DataPipelineServiceProcessorPayload.  # noqa: E501
        :rtype: DataPipelineServiceProcessorPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> DataPipelineServiceProcessorType:
        """Gets the type of this DataPipelineServiceProcessorPayload.


        :return: The type of this DataPipelineServiceProcessorPayload.
        :rtype: DataPipelineServiceProcessorType
        """
        return self._type

    @type.setter
    def type(self, type: DataPipelineServiceProcessorType):
        """Sets the type of this DataPipelineServiceProcessorPayload.


        :param type: The type of this DataPipelineServiceProcessorPayload.
        :type type: DataPipelineServiceProcessorType
        """

        self._type = type

    @property
    def filename(self) -> str:
        """Gets the filename of this DataPipelineServiceProcessorPayload.


        :return: The filename of this DataPipelineServiceProcessorPayload.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this DataPipelineServiceProcessorPayload.


        :param filename: The filename of this DataPipelineServiceProcessorPayload.
        :type filename: str
        """

        self._filename = filename

    @property
    def string_encoded_payload(self) -> ByteArray:
        """Gets the string_encoded_payload of this DataPipelineServiceProcessorPayload.


        :return: The string_encoded_payload of this DataPipelineServiceProcessorPayload.
        :rtype: ByteArray
        """
        return self._string_encoded_payload

    @string_encoded_payload.setter
    def string_encoded_payload(self, string_encoded_payload: ByteArray):
        """Sets the string_encoded_payload of this DataPipelineServiceProcessorPayload.


        :param string_encoded_payload: The string_encoded_payload of this DataPipelineServiceProcessorPayload.
        :type string_encoded_payload: ByteArray
        """
        if string_encoded_payload is not None and not re.search('^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', string_encoded_payload):  # noqa: E501
            raise ValueError("Invalid value for `string_encoded_payload`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._string_encoded_payload = string_encoded_payload
