# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_pipeline_service_identifier import DataPipelineServiceIdentifier  # noqa: F401,E501
from swagger_server import util


class DataPipelineServiceTopicPipeline(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, idtopic: DataPipelineServiceIdentifier=None, idpipeline: DataPipelineServiceIdentifier=None):  # noqa: E501
        """DataPipelineServiceTopicPipeline - a model defined in Swagger

        :param idtopic: The idtopic of this DataPipelineServiceTopicPipeline.  # noqa: E501
        :type idtopic: DataPipelineServiceIdentifier
        :param idpipeline: The idpipeline of this DataPipelineServiceTopicPipeline.  # noqa: E501
        :type idpipeline: DataPipelineServiceIdentifier
        """
        self.swagger_types = {
            'idtopic': DataPipelineServiceIdentifier,
            'idpipeline': DataPipelineServiceIdentifier
        }

        self.attribute_map = {
            'idtopic': 'idtopic',
            'idpipeline': 'idpipeline'
        }

        self._idtopic = idtopic
        self._idpipeline = idpipeline

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceTopicPipeline':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceTopicPipeline of this DataPipelineServiceTopicPipeline.  # noqa: E501
        :rtype: DataPipelineServiceTopicPipeline
        """
        return util.deserialize_model(dikt, cls)

    @property
    def idtopic(self) -> DataPipelineServiceIdentifier:
        """Gets the idtopic of this DataPipelineServiceTopicPipeline.


        :return: The idtopic of this DataPipelineServiceTopicPipeline.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._idtopic

    @idtopic.setter
    def idtopic(self, idtopic: DataPipelineServiceIdentifier):
        """Sets the idtopic of this DataPipelineServiceTopicPipeline.


        :param idtopic: The idtopic of this DataPipelineServiceTopicPipeline.
        :type idtopic: DataPipelineServiceIdentifier
        """

        self._idtopic = idtopic

    @property
    def idpipeline(self) -> DataPipelineServiceIdentifier:
        """Gets the idpipeline of this DataPipelineServiceTopicPipeline.


        :return: The idpipeline of this DataPipelineServiceTopicPipeline.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._idpipeline

    @idpipeline.setter
    def idpipeline(self, idpipeline: DataPipelineServiceIdentifier):
        """Sets the idpipeline of this DataPipelineServiceTopicPipeline.


        :param idpipeline: The idpipeline of this DataPipelineServiceTopicPipeline.
        :type idpipeline: DataPipelineServiceIdentifier
        """

        self._idpipeline = idpipeline
