#ACUMOS
#================================================================================
#Copyright @ 2018 AT&T Intellectual Property. All rights reserved.
#================================================================================
#This Acumos software file is distributed by AT&T under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#This file is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and 
#limitations under the License.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataPipelineServiceKVPair(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, key: str=None, value: str=None):  # noqa: E501
        """DataPipelineServiceKVPair - a model defined in Swagger

        :param key: The key of this DataPipelineServiceKVPair.  # noqa: E501
        :type key: str
        :param value: The value of this DataPipelineServiceKVPair.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'key': str,
            'value': str
        }

        self.attribute_map = {
            'key': 'key',
            'value': 'value'
        }

        self._key = key
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceKVPair':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceKVPair of this DataPipelineServiceKVPair.  # noqa: E501
        :rtype: DataPipelineServiceKVPair
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this DataPipelineServiceKVPair.


        :return: The key of this DataPipelineServiceKVPair.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this DataPipelineServiceKVPair.


        :param key: The key of this DataPipelineServiceKVPair.
        :type key: str
        """

        self._key = key

    @property
    def value(self) -> str:
        """Gets the value of this DataPipelineServiceKVPair.


        :return: The value of this DataPipelineServiceKVPair.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this DataPipelineServiceKVPair.


        :param value: The value of this DataPipelineServiceKVPair.
        :type value: str
        """

        self._value = value
