# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_pipeline_service_identifier import DataPipelineServiceIdentifier  # noqa: F401,E501
from swagger_server import util


class DataPipelineServiceTopicPipeline(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, topic: DataPipelineServiceIdentifier=None, pipeline: DataPipelineServiceIdentifier=None):  # noqa: E501
        """DataPipelineServiceTopicPipeline - a model defined in Swagger

        :param topic: The topic of this DataPipelineServiceTopicPipeline.  # noqa: E501
        :type topic: DataPipelineServiceIdentifier
        :param pipeline: The pipeline of this DataPipelineServiceTopicPipeline.  # noqa: E501
        :type pipeline: DataPipelineServiceIdentifier
        """
        self.swagger_types = {
            'topic': DataPipelineServiceIdentifier,
            'pipeline': DataPipelineServiceIdentifier
        }

        self.attribute_map = {
            'topic': 'topic',
            'pipeline': 'pipeline'
        }

        self._topic = topic
        self._pipeline = pipeline

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceTopicPipeline':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceTopicPipeline of this DataPipelineServiceTopicPipeline.  # noqa: E501
        :rtype: DataPipelineServiceTopicPipeline
        """
        return util.deserialize_model(dikt, cls)

    @property
    def topic(self) -> DataPipelineServiceIdentifier:
        """Gets the topic of this DataPipelineServiceTopicPipeline.


        :return: The topic of this DataPipelineServiceTopicPipeline.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._topic

    @topic.setter
    def topic(self, topic: DataPipelineServiceIdentifier):
        """Sets the topic of this DataPipelineServiceTopicPipeline.


        :param topic: The topic of this DataPipelineServiceTopicPipeline.
        :type topic: DataPipelineServiceIdentifier
        """

        self._topic = topic

    @property
    def pipeline(self) -> DataPipelineServiceIdentifier:
        """Gets the pipeline of this DataPipelineServiceTopicPipeline.


        :return: The pipeline of this DataPipelineServiceTopicPipeline.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._pipeline

    @pipeline.setter
    def pipeline(self, pipeline: DataPipelineServiceIdentifier):
        """Sets the pipeline of this DataPipelineServiceTopicPipeline.


        :param pipeline: The pipeline of this DataPipelineServiceTopicPipeline.
        :type pipeline: DataPipelineServiceIdentifier
        """

        self._pipeline = pipeline
