# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataPipelineServiceIdentifierType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    READ_DATASOURCE = "READ_DATASOURCE"
    PUBLISHER_PROCESSOR = "PUBLISHER_PROCESSOR"
    SUBSCRIBER_PROCESSOR = "SUBSCRIBER_PROCESSOR"
    TRANSFORMER_PROCESSOR = "TRANSFORMER_PROCESSOR"
    PIPELINEPOOL = "PIPELINEPOOL"
    TOPIC = "TOPIC"
    PROCESSOR = "PROCESSOR"
    PIPELINE = "PIPELINE"
    DATA = "DATA"
    WRITE_DATASOURCE = "WRITE_DATASOURCE"
    SINK_PROCESSOR = "SINK_PROCESSOR"

    def __init__(self):  # noqa: E501
        """DataPipelineServiceIdentifierType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceIdentifierType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceIdentifierType of this DataPipelineServiceIdentifierType.  # noqa: E501
        :rtype: DataPipelineServiceIdentifierType
        """
        return util.deserialize_model(dikt, cls)
