# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_pipeline_service_identifier import DataPipelineServiceIdentifier  # noqa: F401,E501
from swagger_server import util


class DataPipelineServiceObjects(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, objects: List[DataPipelineServiceIdentifier]=None):  # noqa: E501
        """DataPipelineServiceObjects - a model defined in Swagger

        :param objects: The objects of this DataPipelineServiceObjects.  # noqa: E501
        :type objects: List[DataPipelineServiceIdentifier]
        """
        self.swagger_types = {
            'objects': List[DataPipelineServiceIdentifier]
        }

        self.attribute_map = {
            'objects': 'objects'
        }

        self._objects = objects

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceObjects':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceObjects of this DataPipelineServiceObjects.  # noqa: E501
        :rtype: DataPipelineServiceObjects
        """
        return util.deserialize_model(dikt, cls)

    @property
    def objects(self) -> List[DataPipelineServiceIdentifier]:
        """Gets the objects of this DataPipelineServiceObjects.


        :return: The objects of this DataPipelineServiceObjects.
        :rtype: List[DataPipelineServiceIdentifier]
        """
        return self._objects

    @objects.setter
    def objects(self, objects: List[DataPipelineServiceIdentifier]):
        """Sets the objects of this DataPipelineServiceObjects.


        :param objects: The objects of this DataPipelineServiceObjects.
        :type objects: List[DataPipelineServiceIdentifier]
        """

        self._objects = objects
