# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataPipelineServiceExtract(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: List[str]=None):  # noqa: E501
        """DataPipelineServiceExtract - a model defined in Swagger

        :param data: The data of this DataPipelineServiceExtract.  # noqa: E501
        :type data: List[str]
        """
        self.swagger_types = {
            'data': List[str]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceExtract':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceExtract of this DataPipelineServiceExtract.  # noqa: E501
        :rtype: DataPipelineServiceExtract
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[str]:
        """Gets the data of this DataPipelineServiceExtract.


        :return: The data of this DataPipelineServiceExtract.
        :rtype: List[str]
        """
        return self._data

    @data.setter
    def data(self, data: List[str]):
        """Sets the data of this DataPipelineServiceExtract.


        :param data: The data of this DataPipelineServiceExtract.
        :type data: List[str]
        """

        self._data = data
