#ACUMOS
#================================================================================
#Copyright Â© 2018 AT&T Intellectual Property. All rights reserved.
#================================================================================
#This Acumos software file is distributed by AT&Tunder the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#This file is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and 
#limitations under the License.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_pipeline_service_identifier import DataPipelineServiceIdentifier  # noqa: F401,E501
from swagger_server import util


class DataPipelineServiceDataSourcePool(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, iddatasource: DataPipelineServiceIdentifier=None, idpool: DataPipelineServiceIdentifier=None):  # noqa: E501
        """DataPipelineServiceDataSourcePool - a model defined in Swagger

        :param iddatasource: The iddatasource of this DataPipelineServiceDataSourcePool.  # noqa: E501
        :type iddatasource: DataPipelineServiceIdentifier
        :param idpool: The idpool of this DataPipelineServiceDataSourcePool.  # noqa: E501
        :type idpool: DataPipelineServiceIdentifier
        """
        self.swagger_types = {
            'iddatasource': DataPipelineServiceIdentifier,
            'idpool': DataPipelineServiceIdentifier
        }

        self.attribute_map = {
            'iddatasource': 'iddatasource',
            'idpool': 'idpool'
        }

        self._iddatasource = iddatasource
        self._idpool = idpool

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceDataSourcePool':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceDataSourcePool of this DataPipelineServiceDataSourcePool.  # noqa: E501
        :rtype: DataPipelineServiceDataSourcePool
        """
        return util.deserialize_model(dikt, cls)

    @property
    def iddatasource(self) -> DataPipelineServiceIdentifier:
        """Gets the iddatasource of this DataPipelineServiceDataSourcePool.


        :return: The iddatasource of this DataPipelineServiceDataSourcePool.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._iddatasource

    @iddatasource.setter
    def iddatasource(self, iddatasource: DataPipelineServiceIdentifier):
        """Sets the iddatasource of this DataPipelineServiceDataSourcePool.


        :param iddatasource: The iddatasource of this DataPipelineServiceDataSourcePool.
        :type iddatasource: DataPipelineServiceIdentifier
        """

        self._iddatasource = iddatasource

    @property
    def idpool(self) -> DataPipelineServiceIdentifier:
        """Gets the idpool of this DataPipelineServiceDataSourcePool.


        :return: The idpool of this DataPipelineServiceDataSourcePool.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._idpool

    @idpool.setter
    def idpool(self, idpool: DataPipelineServiceIdentifier):
        """Sets the idpool of this DataPipelineServiceDataSourcePool.


        :param idpool: The idpool of this DataPipelineServiceDataSourcePool.
        :type idpool: DataPipelineServiceIdentifier
        """

        self._idpool = idpool
