#ACUMOS
#================================================================================
#Copyright @ 2018 AT&T Intellectual Property. All rights reserved.
#================================================================================
#This Acumos software file is distributed by AT&T under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#This file is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and 
#limitations under the License.

# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_pipeline_service_identifier import DataPipelineServiceIdentifier  # noqa: F401,E501
from swagger_server import util


class DataPipelineServiceProcessorTopic(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, idprocessor: DataPipelineServiceIdentifier=None, idtopic: DataPipelineServiceIdentifier=None, iddatasource: DataPipelineServiceIdentifier=None):  # noqa: E501
        """DataPipelineServiceProcessorTopic - a model defined in Swagger

        :param idprocessor: The idprocessor of this DataPipelineServiceProcessorTopic.  # noqa: E501
        :type idprocessor: DataPipelineServiceIdentifier
        :param idtopic: The idtopic of this DataPipelineServiceProcessorTopic.  # noqa: E501
        :type idtopic: DataPipelineServiceIdentifier
        :param iddatasource: The iddatasource of this DataPipelineServiceProcessorTopic.  # noqa: E501
        :type iddatasource: DataPipelineServiceIdentifier
        """
        self.swagger_types = {
            'idprocessor': DataPipelineServiceIdentifier,
            'idtopic': DataPipelineServiceIdentifier,
            'iddatasource': DataPipelineServiceIdentifier
        }

        self.attribute_map = {
            'idprocessor': 'idprocessor',
            'idtopic': 'idtopic',
            'iddatasource': 'iddatasource'
        }

        self._idprocessor = idprocessor
        self._idtopic = idtopic
        self._iddatasource = iddatasource

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipelineServiceProcessorTopic':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipelineServiceProcessorTopic of this DataPipelineServiceProcessorTopic.  # noqa: E501
        :rtype: DataPipelineServiceProcessorTopic
        """
        return util.deserialize_model(dikt, cls)

    @property
    def idprocessor(self) -> DataPipelineServiceIdentifier:
        """Gets the idprocessor of this DataPipelineServiceProcessorTopic.


        :return: The idprocessor of this DataPipelineServiceProcessorTopic.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._idprocessor

    @idprocessor.setter
    def idprocessor(self, idprocessor: DataPipelineServiceIdentifier):
        """Sets the idprocessor of this DataPipelineServiceProcessorTopic.


        :param idprocessor: The idprocessor of this DataPipelineServiceProcessorTopic.
        :type idprocessor: DataPipelineServiceIdentifier
        """

        self._idprocessor = idprocessor

    @property
    def idtopic(self) -> DataPipelineServiceIdentifier:
        """Gets the idtopic of this DataPipelineServiceProcessorTopic.


        :return: The idtopic of this DataPipelineServiceProcessorTopic.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._idtopic

    @idtopic.setter
    def idtopic(self, idtopic: DataPipelineServiceIdentifier):
        """Sets the idtopic of this DataPipelineServiceProcessorTopic.


        :param idtopic: The idtopic of this DataPipelineServiceProcessorTopic.
        :type idtopic: DataPipelineServiceIdentifier
        """

        self._idtopic = idtopic

    @property
    def iddatasource(self) -> DataPipelineServiceIdentifier:
        """Gets the iddatasource of this DataPipelineServiceProcessorTopic.


        :return: The iddatasource of this DataPipelineServiceProcessorTopic.
        :rtype: DataPipelineServiceIdentifier
        """
        return self._iddatasource

    @iddatasource.setter
    def iddatasource(self, iddatasource: DataPipelineServiceIdentifier):
        """Sets the iddatasource of this DataPipelineServiceProcessorTopic.


        :param iddatasource: The iddatasource of this DataPipelineServiceProcessorTopic.
        :type iddatasource: DataPipelineServiceIdentifier
        """

        self._iddatasource = iddatasource
